version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      PORT: 8000
      NUXT_PUBLIC_API_BASE: http://nginx:80/api
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    stdin_open: true
    tty: true
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      CDN_BASE_URL: http://localhost
    networks:
      - app-network
      
  nginx:
    image: nginx:1.21-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge