# fly.toml app configuration file generated for kisi-backend on 2023-12-04T19:42:55+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "kisi-backend"
primary_region = "cdg"

[env]
  CDN_BASE_URL = "https://kisi-backend.fly.dev"
  CLIENT_URL = "https://kisi-frontend.fly.dev"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
